stores:
  json:
    indent: 2
  yaml:
    indent: 2
# Define age keys as YAML anchors for reuse
keys:
  # Host keys
  hosts:
    carbon: &host_carbon age10ewrmr20gy5pc74tyygws7z80jmh4yn5f4e4sh96mznrvw347ecqjc2ms7
    altdesk: &host_altdesk age1gwk0m9n4mrr7h572kkjxtkkl4p0t2mfc9f7ms0560s63x4pawgzq433tca
    desktop: &host_desktop age18y57gdahad7zhrrgj2m4dd7fcgwfn4gpmxe9mhcrue8suq8e8c3stzd0ge
    bifrost: &host_bifrost age1rs5rev3ks20s67052nshr5asqctvylrlytksjrfsns8e93t78dssr7wzg9
    niflheim: &host_niflheim age1rs5rev3ks20s67052nshr5asqctvylrlytksjrfsns8e93t78dssr7wzg9
  # User keys per machine
  users:
    alapshin_carbon: &user_alapshin_carbon age18cxypcgpy8ln3sch0j20thaps65w7nrtv6jvt3rrm5gysldq2vrqzgjf09
    alapshin_altdesk: &user_alapshin_altdesk age1sfed5wmvj00snjxrtds0zt83kt7ffek6mdtgfykum6uzxnphwg4qp5rv2l
    alapshin_desktop: &user_alapshin_desktop age1k2t56rsp2xvdsvjxraytyfufedxcl7z548tc9dzdhzqpq9yyfc9sz2h70e
    alapshin_macbook: &user_alapshin_macbook age14hh5cmhznwdpnyehtqlm2qzsl6m3kud2pn4rvy2jlp3yvqmj6e0qcrgh69
creation_rules:
  # Common secrets - accessible by all hosts and users
  - path_regex: hosts/common/secrets.*
    key_groups:
      - age:
          - *host_carbon
          - *host_altdesk
          - *host_desktop
          - *host_bifrost
          - *host_niflheim
          - *user_alapshin_carbon
          - *user_alapshin_altdesk
          - *user_alapshin_desktop
          - *user_alapshin_macbook
  # Personal hosts secrets - accessible by all personal hosts
  - path_regex: hosts/personal/secrets.*
    key_groups:
      - age:
          - *host_carbon
          - *host_altdesk
          - *host_desktop
          - *user_alapshin_carbon
          - *user_alapshin_altdesk
          - *user_alapshin_desktop
  - path_regex: hosts/carbon/secrets.*
    key_groups:
      - age:
          - *host_carbon
          - *user_alapshin_carbon
  - path_regex: hosts/desktop/secrets.*
    key_groups:
      - age:
          - *host_desktop
          - *user_alapshin_desktop
  - path_regex: hosts/altdesk/secrets.*
    key_groups:
      - age:
          - *host_altdesk
          - *user_alapshin_altdesk
  - path_regex: hosts/bifrost/secrets.*
    key_groups:
      - age:
          - *host_bifrost
          - *user_alapshin_carbon
          - *user_alapshin_desktop
          - *user_alapshin_macbook
  - path_regex: hosts/niflheim/secrets.*
    key_groups:
      - age:
          - *host_niflheim
          - *user_alapshin_carbon
          - *user_alapshin_desktop
          - *user_alapshin_macbook
  # user-specific secrets
  - path_regex: users/alapshin/secrets.*
    key_groups:
      - age:
          - *user_alapshin_carbon
          - *user_alapshin_altdesk
          - *user_alapshin_desktop
          - *user_alapshin_macbook
