stores:
  json:
    indent: 2
  yaml:
    indent: 2
creation_rules:
  - path_regex: hosts/common/secrets.*
    key_groups:
      - age:
          # bifrost
          - age1rs5rev3ks20s67052nshr5asqctvylrlytksjrfsns8e93t78dssr7wzg9
          # niflheim
          - age1rs5rev3ks20s67052nshr5asqctvylrlytksjrfsns8e93t78dssr7wzg9
          # carbon
          - age10ewrmr20gy5pc74tyygws7z80jmh4yn5f4e4sh96mznrvw347ecqjc2ms7
          # altdesk
          - age1gwk0m9n4mrr7h572kkjxtkkl4p0t2mfc9f7ms0560s63x4pawgzq433tca
          # desktop
          - age18y57gdahad7zhrrgj2m4dd7fcgwfn4gpmxe9mhcrue8suq8e8c3stzd0ge
          # alapshin-at-carbon
          - age18cxypcgpy8ln3sch0j20thaps65w7nrtv6jvt3rrm5gysldq2vrqzgjf09
          # alapshin-at-altdesk
          - age1sfed5wmvj00snjxrtds0zt83kt7ffek6mdtgfykum6uzxnphwg4qp5rv2l
          # alapshin-at-desktop
          - age1k2t56rsp2xvdsvjxraytyfufedxcl7z548tc9dzdhzqpq9yyfc9sz2h70e
          # alapshin-at-macbook
          - age14hh5cmhznwdpnyehtqlm2qzsl6m3kud2pn4rvy2jlp3yvqmj6e0qcrgh69
  - path_regex: hosts/personal/secrets.*
    key_groups:
      - age:
          # carbon
          - age10ewrmr20gy5pc74tyygws7z80jmh4yn5f4e4sh96mznrvw347ecqjc2ms7
          # altdesk
          - age1gwk0m9n4mrr7h572kkjxtkkl4p0t2mfc9f7ms0560s63x4pawgzq433tca
          # desktop
          - age18y57gdahad7zhrrgj2m4dd7fcgwfn4gpmxe9mhcrue8suq8e8c3stzd0ge
          # alapshin-at-carbon
          - age18cxypcgpy8ln3sch0j20thaps65w7nrtv6jvt3rrm5gysldq2vrqzgjf09
          # alapshin-at-altdesk
          - age1sfed5wmvj00snjxrtds0zt83kt7ffek6mdtgfykum6uzxnphwg4qp5rv2l
          # alapshin-at-desktop
          - age1k2t56rsp2xvdsvjxraytyfufedxcl7z548tc9dzdhzqpq9yyfc9sz2h70e
  - path_regex: hosts/carbon/secrets.*
    key_groups:
      - age:
          # carbon
          - age10ewrmr20gy5pc74tyygws7z80jmh4yn5f4e4sh96mznrvw347ecqjc2ms7
          # alapshin-at-carbon
          - age18cxypcgpy8ln3sch0j20thaps65w7nrtv6jvt3rrm5gysldq2vrqzgjf09
  - path_regex: hosts/desktop/secrets.*
    key_groups:
      - age:
          # desktop
          - age18y57gdahad7zhrrgj2m4dd7fcgwfn4gpmxe9mhcrue8suq8e8c3stzd0ge
          # alapshin-at-desktop
          - age1k2t56rsp2xvdsvjxraytyfufedxcl7z548tc9dzdhzqpq9yyfc9sz2h70e
  - path_regex: hosts/altdesk/secrets.*
    key_groups:
      - age:
          # altdesk
          - age1gwk0m9n4mrr7h572kkjxtkkl4p0t2mfc9f7ms0560s63x4pawgzq433tca
          # alapshin-at-altdesk
          - age1sfed5wmvj00snjxrtds0zt83kt7ffek6mdtgfykum6uzxnphwg4qp5rv2l
  - path_regex: hosts/bifrost/secrets.*
    key_groups:
      - age:
          # bifrost
          - age1rs5rev3ks20s67052nshr5asqctvylrlytksjrfsns8e93t78dssr7wzg9
          # alapshin-at-carbon
          - age18cxypcgpy8ln3sch0j20thaps65w7nrtv6jvt3rrm5gysldq2vrqzgjf09
          # alapshin-at-desktop
          - age1k2t56rsp2xvdsvjxraytyfufedxcl7z548tc9dzdhzqpq9yyfc9sz2h70e
  - path_regex: hosts/niflheim/secrets.*
    key_groups:
      - age:
          # niflheim
          - age1rs5rev3ks20s67052nshr5asqctvylrlytksjrfsns8e93t78dssr7wzg9
          # alapshin-at-carbon
          - age18cxypcgpy8ln3sch0j20thaps65w7nrtv6jvt3rrm5gysldq2vrqzgjf09
          # alapshin-at-desktop
          - age1k2t56rsp2xvdsvjxraytyfufedxcl7z548tc9dzdhzqpq9yyfc9sz2h70e
  - path_regex: users/alapshin/secrets.*
    key_groups:
      - age:
          # alapshin-at-carbon
          - age18cxypcgpy8ln3sch0j20thaps65w7nrtv6jvt3rrm5gysldq2vrqzgjf09
          # alapshin-at-altdesk
          - age1sfed5wmvj00snjxrtds0zt83kt7ffek6mdtgfykum6uzxnphwg4qp5rv2l
          # alapshin-at-desktop
          - age1k2t56rsp2xvdsvjxraytyfufedxcl7z548tc9dzdhzqpq9yyfc9sz2h70e
          # alapshin-at-macbook
          - age14hh5cmhznwdpnyehtqlm2qzsl6m3kud2pn4rvy2jlp3yvqmj6e0qcrgh69
