keys:
  - &altdesk age1gwk0m9n4mrr7h572kkjxtkkl4p0t2mfc9f7ms0560s63x4pawgzq433tca
  - &desktop age18y57gdahad7zhrrgj2m4dd7fcgwfn4gpmxe9mhcrue8suq8e8c3stzd0ge
  - &alapshin age1k2t56rsp2xvdsvjxraytyfufedxcl7z548tc9dzdhzqpq9yyfc9sz2h70e

creation_rules:
  - path_regex: secrets/.*$
    key_groups:
      - age:
        - *altdesk
        - *desktop
        - *alapshin
