borg_key: ENC[AES256_GCM,data:Jfh0L9/jww8/nLBP/IZnEw==,iv:ixKLbUKDcK20k2jx6mg6NeNZAJdfWlamkTsj4mJkvBk=,tag:xCi3U+4UqZglsMScwE/png==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18y57gdahad7zhrrgj2m4dd7fcgwfn4gpmxe9mhcrue8suq8e8c3stzd0ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TUtSblNBc2FPRENUbnoy
            cUx1ZDloT2FZR2tncVRaNHNkVFZrVFQrYm1VCmljdG1tZGN0a0c4YVcxUXExdzJi
            TnNNWXlFMEZRc2UwUjFMeHFtVWcrOHcKLS0tIGNxZk5KS3I2aUpPSWVmMGtuRXFz
            eHRtUk4rOUxMY0ozKzJCWFRiaHRzYkEKuKtZSenicazo3D4VszHZXGQ0HzXfWQ7T
            j0zNAADX1ZZdcM9QLFLp0uMMsQNm8lTCGTODUfiN+34k9su8avXZkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k2t56rsp2xvdsvjxraytyfufedxcl7z548tc9dzdhzqpq9yyfc9sz2h70e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z1hqR2JMcURiZFZreUl3
            MXQ3YSsrNGRaQkw2czVHWVRXZjNVRUVMandVCklsblpJcXJGWDA0czYxN2dvRkFC
            VlFQeDNEMU5DV2ppaWJRS3ZYMUNDN28KLS0tIEtMM1ExMldJN3phVUZSZmhUc0xw
            OVF4ZDl1VlFwTlNrMDFFUXp1R0c5RjgKXT51yrB6YI//Z/0undLehxdHBWbbo3n7
            PdaVVi11ngYROx2OmFYR1nxjtxENj3WlGRBY4b907NTmkRyaQ5hi0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-02T17:17:57Z"
    mac: ENC[AES256_GCM,data:wCbctcXRzI6ygqv+B5GDVVXNhRuBr5GXi2P50DZly+TYmrmyy7Vf/Sw3M4IiYwTL3AEcvVH1pR3ssD8ogwUqlpV2uqmDU5RKLw4r8UGKPCoWQnJGixLFJFCfxRq1zA3mKwGf6yiYgH3wwJ/BiL+gNrWOeN77GqsP/sZw9wyEbH0=,iv:KKdT1TyoNRyDs7WCMbFWBiCjcHeN4EAYejGfIcyLbO4=,tag:oWSwHH5jqZPIaOMVu5IlRA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
